export const XMTP_CONSTANTS = {
  MAX_RETRY_ATTEMPTS: 3,
  RETRY_DELAY: 1000,
  MESSAGE_BATCH_SIZE: 50,
  MAX_MESSAGE_SIZE: 10000, // 10KB
  STREAM_TIMEOUT: 30000, // 30 seconds
  INITIALIZATION_TIMEOUT: 10000, // 10 seconds
} as const;

export const ERROR_CODES = {
  CLIENT_NOT_INITIALIZED: 'CLIENT_NOT_INITIALIZED',
  CONVERSATION_ERROR: 'CONVERSATION_ERROR',
  MESSAGE_ERROR: 'MESSAGE_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR',
  TIMEOUT_ERROR: 'TIMEOUT_ERROR',
} as const;