export const LAYOUT = {
  HEADER_HEIGHT: 80,
  FOOTER_HEIGHT: 48,
  MENU_HEIGHT: 48,
  MOBILE_PADDING: 16,
  MOBILE_WIDGET_SPACING: 12,
  MOBILE_HEADER_ACTIONS_HEIGHT: 56,
  MIN_WIDGET_WIDTH: 300,
  MIN_WIDGET_HEIGHT: 200,
  WIDGET_MARGIN: 16,
  Z_INDEX: {
    BACKGROUND: -1,
    BASE: 0,
    WIDGET: 10,
    HEADER: 60,
    MENU: 55,
    MODAL: 70,
    PORTAL: 100
  }
} as const;

export const BREAKPOINTS = {
  MOBILE: 768,
  TABLET: 1024,
  DESKTOP: 1280
} as const;
